<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSendChat</name>
   <tag></tag>
   <elementGuidId>ea09cf1e-8454-41fc-899f-c7e7c54339e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.VizExIconButton__AbstractVizExIconButton-im1tv5-0.eQvYjF.chat-send-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>898c568a-75a5-4f52-bab9-50485b69510c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VizExIconButton__AbstractVizExIconButton-im1tv5-0 eQvYjF chat-send-button</value>
      <webElementGuid>fcc3ac51-ac45-4e26-ad14-bc09e0ef1c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-send-button</value>
      <webElementGuid>b834f581-0a38-41fa-bd7d-ce2ada61275a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>MessageEditor-VizExIconButton</value>
      <webElementGuid>2f2b8d37-e922-4abe-a8ee-6dfab95e37f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>6008b010-4c29-46eb-aedd-e7024191af99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>send message</value>
      <webElementGuid>3c6516ff-e3ff-4352-97f7-1825ec8f08a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current-view-component&quot;)/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetStyleWrapper-q9otpi-0 ikLZth&quot;]/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetContentStyleWrapper-q9otpi-1 gaTWey chat-widget&quot;]/div[@class=&quot;VisitorWidget__WidgetBodyDiv-sc-1casxq4-0 BJKvU&quot;]/div[@class=&quot;UnifiedThreadViewWrapperWithDragUpload__UnifiedThreadViewWrapper-s4ctvh-0 ftjQdo&quot;]/div[@class=&quot;input-container m-bottom-2&quot;]/div[@class=&quot;MessageComposer__InputWrapper-eu8qwr-1 hwHFTi&quot;]/div[@class=&quot;display-flex flex-row m-left-1 no-shrink&quot;]/button[@class=&quot;VizExIconButton__AbstractVizExIconButton-im1tv5-0 eQvYjF chat-send-button&quot;]</value>
      <webElementGuid>74250885-bc6a-4d39-bc45-334c40c8e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Exercise3/iframe_concat(id(, , hubspot-conversations-iframe, , ))_hubspot-conversations-iframe</value>
      <webElementGuid>a50691e4-cfe2-4a08-a3b3-89d6bd707881</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div[2]/button</value>
      <webElementGuid>fcb01357-b719-409d-b76a-318332a38f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tesst'])[1]/following::button[1]</value>
      <webElementGuid>17c9099f-5894-4030-bb0f-5a1222ba2d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Got any questions? I', &quot;'&quot;, 'm happy to help.')])[1]/following::button[1]</value>
      <webElementGuid>2691522a-889f-4570-97dc-b261d176cb2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='live chat'])[1]/preceding::button[1]</value>
      <webElementGuid>8782c5dd-6e37-4781-be94-c4d07680c28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>beef9e87-6362-4434-8d59-79e729b4e1dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
