<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , hubspot-conversations-iframe, , ))_hubspot-conversations-iframe</name>
   <tag></tag>
   <elementGuidId>7e792ee4-acfd-45c3-888f-e730a7d3c6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubspot-conversations-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='hubspot-conversations-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7a0da2b0-762f-4db8-97cc-e35584f6be6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.hubspot.com/conversations-visitor/6856823/threads/utk/e7b7ba187b5e43919fd21de14c6087da?uuid=23cd0e86bfd5459b8718e4ed8b0040ba&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=phptravels.com&amp;inApp53=false&amp;messagesUtk=e7b7ba187b5e43919fd21de14c6087da&amp;url=https%3A%2F%2Fphptravels.com%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false</value>
      <webElementGuid>4e9350f4-2aea-4379-ae92-388c00191442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubspot-conversations-iframe</value>
      <webElementGuid>c19aa6af-80c4-48cd-a37d-88fee31a8144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>76c29a96-9ad8-48c1-ac7a-889acd3fffb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Widget</value>
      <webElementGuid>e8faf9e4-47b2-4b65-b45c-e7db10d0ec08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-widget-iframe</value>
      <webElementGuid>c74a0d47-c3ce-4fbb-aae3-71da4c218118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubspot-conversations-iframe&quot;)</value>
      <webElementGuid>a6cec193-4c70-45a1-b4e3-de9c05b0883e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='hubspot-conversations-iframe']</value>
      <webElementGuid>a791d45f-591b-4aef-b6bd-76cc4664dc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hubspot-messages-iframe-container']/iframe</value>
      <webElementGuid>dd0cf4a3-d4b8-4ce6-81ec-aa465c6ca8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>0732418f-1bbf-4d4d-bcd5-5b54e480f18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.hubspot.com/conversations-visitor/6856823/threads/utk/e7b7ba187b5e43919fd21de14c6087da?uuid=23cd0e86bfd5459b8718e4ed8b0040ba&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=phptravels.com&amp;inApp53=false&amp;messagesUtk=e7b7ba187b5e43919fd21de14c6087da&amp;url=https%3A%2F%2Fphptravels.com%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false' and @id = 'hubspot-conversations-iframe']</value>
      <webElementGuid>cb8e392e-6d86-4d07-89c8-47a2ccf4f620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
