<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtChatContent</name>
   <tag></tag>
   <elementGuidId>2b150fab-84bc-4432-ae2a-46a997c61534</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.VizExExpandingInput__StyledInput-sc-616wwd-0.cXlzG.widget-textarea.message-box</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e61f2cfa-f61e-4ee4-aad5-41538d21380a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Write a message</value>
      <webElementGuid>0901a8a4-e66d-41f4-88f9-350d9057c2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7252f82-27eb-475b-b3dc-c44072fd020f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4b1cdd56-5b87-4f3a-bb39-2112192a82c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VizExExpandingInput__StyledInput-sc-616wwd-0 cXlzG widget-textarea message-box</value>
      <webElementGuid>1b324c8b-378f-4640-986e-06cd02f63d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>widget-textarea</value>
      <webElementGuid>5b100511-584a-47b3-b8b5-0e6e37748a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>220fa950-8169-423e-9211-0f8c35644b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Write a message</value>
      <webElementGuid>ace5e777-ccc9-44b3-8161-84ee5339a350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d4614b7-d1bf-430f-871a-15d87562e1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5450b37-857e-42a5-9945-661de4d81182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>VizExExpandingInput</value>
      <webElementGuid>4b57cbbd-387e-4fc2-866c-4affc943974d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current-view-component&quot;)/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetStyleWrapper-q9otpi-0 ikLZth&quot;]/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetContentStyleWrapper-q9otpi-1 gaTWey chat-widget&quot;]/div[@class=&quot;VisitorWidget__WidgetBodyDiv-sc-1casxq4-0 BJKvU&quot;]/div[@class=&quot;UnifiedThreadViewWrapperWithDragUpload__UnifiedThreadViewWrapper-s4ctvh-0 ftjQdo&quot;]/div[@class=&quot;input-container m-bottom-2&quot;]/div[@class=&quot;MessageComposer__InputWrapper-eu8qwr-1 hwHFTi&quot;]/div[@class=&quot;VizExFormControl__FormControlWrapper-e31d3f-0 gRalQW&quot;]/div[@class=&quot;VizExExpandingInput__StyledInput-sc-616wwd-0 cXlzG widget-textarea message-box&quot;]</value>
      <webElementGuid>b25f9b05-5341-4e7e-a97d-04ac6f370404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Exercise3/iframe_concat(id(, , hubspot-conversations-iframe, , ))_hubspot-conversations-iframe</value>
      <webElementGuid>cfab10eb-3d32-4b77-878e-69072644e7f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>bbb7f510-4e5b-47cb-96ff-0e1694be453f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>052f66ba-8715-4e69-b019-bbac89f061ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@placeholder = 'Write a message']</value>
      <webElementGuid>9d8cd1b7-3e26-4d41-955d-6af68f36986d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
