<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAgoda</name>
   <tag></tag>
   <elementGuidId>396ae373-c0c4-4862-a17d-d63dfcc56815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/div[2]/div/div[5]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>77ec6838-bc90-40e1-9d01-32fc07c208a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://phptravels.com/assets/data/integrations_img/agoda.png</value>
      <webElementGuid>09f4d0f5-9178-4567-8151-aa30d27758ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100</value>
      <webElementGuid>e0a0f7be-cd35-4950-bb18-4165cd2a55a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agoda</value>
      <webElementGuid>a3bec348-7967-42d9-b124-74c510cd8af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container mt3 mb2&quot;]/div[@class=&quot;row jcc integration g-3&quot;]/div[@class=&quot;col-md-1 col-3 mb1&quot;]/a[@class=&quot;waves-effect&quot;]/img[@class=&quot;w100&quot;]</value>
      <webElementGuid>432a77ee-b60d-4f9d-b6d0-717ed23017f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[5]/a/img</value>
      <webElementGuid>94e19a66-805e-4546-8aec-609a96910e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Agoda']</value>
      <webElementGuid>ff836ca2-2850-49e5-b8d1-39889c5d7e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>123b805d-8330-4719-922f-671746387b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://phptravels.com/assets/data/integrations_img/agoda.png' and @alt = 'Agoda']</value>
      <webElementGuid>f811746e-53c0-42d9-8f69-c5365c425a87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
