<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAgoda</name>
   <tag></tag>
   <elementGuidId>396ae373-c0c4-4862-a17d-d63dfcc56815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div[5]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>492a1c96-1c75-4577-8998-64224adf97b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://phptravels.com/assets/data/integrations_img/agoda.png</value>
      <webElementGuid>313da3df-3fb9-4a64-a94f-3778e73f1ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100</value>
      <webElementGuid>1f5cbdb0-6733-4689-87e9-1d88241b58fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agoda</value>
      <webElementGuid>efaca3ed-b8e9-4424-b442-bd41e1d476dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container mt3 mb2&quot;]/div[@class=&quot;row jcc integration g-3&quot;]/div[@class=&quot;col-md-1 col-3 mb1&quot;]/a[@class=&quot;waves-effect&quot;]/img[@class=&quot;w100&quot;]</value>
      <webElementGuid>d8c4b634-c769-4a35-932c-d62257320157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[5]/a/img</value>
      <webElementGuid>768eae4d-cdc7-406c-b102-61f7665caa38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Agoda']</value>
      <webElementGuid>5c3d2537-1247-46be-8171-1babe15b4815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>0c1b774d-b790-42df-afd2-6a4713a44f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://phptravels.com/assets/data/integrations_img/agoda.png' and @alt = 'Agoda']</value>
      <webElementGuid>8577c9bc-9576-4d8b-a838-b19fb51ccc5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
