<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnIntergration</name>
   <tag></tag>
   <elementGuidId>396ae373-c0c4-4862-a17d-d63dfcc56815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;menu&quot;]/div[1]/ul/li[3]/div/div/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9250cfc5-9ce1-4b21-a244-cf4141204d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://phptravels.com/assets/data/integrations_img/agoda.png</value>
      <webElementGuid>06613cd4-1e1b-4701-8e0b-dbe575f2d9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w100</value>
      <webElementGuid>6727df73-ee8a-44fb-b72e-69494249393e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Agoda</value>
      <webElementGuid>4a4ad0df-b0ac-474c-80a6-8d394b770fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container mt3 mb2&quot;]/div[@class=&quot;row jcc integration g-3&quot;]/div[@class=&quot;col-md-1 col-3 mb1&quot;]/a[@class=&quot;waves-effect&quot;]/img[@class=&quot;w100&quot;]</value>
      <webElementGuid>c04544fc-1d16-45c1-9014-86a280c33943</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[5]/a/img</value>
      <webElementGuid>8b7ca087-b6e1-46fd-ba62-1a3ee2058604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Agoda']</value>
      <webElementGuid>8f2b0be7-2935-430f-884d-887f759e182e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/img</value>
      <webElementGuid>92a812b5-b8ba-4fb1-8f74-77f483017281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://phptravels.com/assets/data/integrations_img/agoda.png' and @alt = 'Agoda']</value>
      <webElementGuid>e929ac7c-8dab-4765-9f03-e4820d110e6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
