<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnProduct</name>
   <tag></tag>
   <elementGuidId>53847669-96e9-4095-8e39-49e830d1b02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;menu&quot;]/div[1]/ul/li[3]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.arrow.waves-effect</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eeb78ff3-6da6-4a7a-b6ef-60debc6e3599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow waves-effect</value>
      <webElementGuid>ea46c970-cf56-4615-a749-7efdf205d7ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.com/integrations</value>
      <webElementGuid>d4998cd4-2899-474f-9375-e7e6ef406206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integrations</value>
      <webElementGuid>0d0d7431-6c24-48ae-80fa-8d5825104197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;nav_left&quot;]/ul[1]/li[3]/div[@class=&quot;link&quot;]/div[@class=&quot;dropdown-content&quot;]/a[@class=&quot;arrow waves-effect&quot;]</value>
      <webElementGuid>04b6e2cb-a248-47bb-8fdf-efc138286d91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/ul/li[3]/div/div/a[2]</value>
      <webElementGuid>dee60483-85f5-4b67-80bd-5b3d4e4d302a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Integrations')]</value>
      <webElementGuid>004e0513-5930-4127-9606-8b931724e72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::a[2]</value>
      <webElementGuid>6956ab21-e7b6-4ad3-af32-c1f4d1de5163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>db60902f-c7f3-4cda-990d-a74717e8d5a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customizations'])[1]/preceding::a[1]</value>
      <webElementGuid>13370d05-c774-473a-9b50-1591fddb40e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::a[2]</value>
      <webElementGuid>56bbbebd-4cc1-49c8-a408-266c6b10c3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Integrations']/parent::*</value>
      <webElementGuid>259c1fa2-f2aa-4115-8ddd-6cc0de643e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.com/integrations')]</value>
      <webElementGuid>886db2ea-8bb4-4367-bfbf-a504460e4540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>9a17c904-979a-4ee0-9aee-ba9c546fcc72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.com/integrations' and (text() = 'Integrations' or . = 'Integrations')]</value>
      <webElementGuid>8db4d5bb-69d6-4219-b542-5c69f8a737e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
