<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnProduct</name>
   <tag></tag>
   <elementGuidId>53847669-96e9-4095-8e39-49e830d1b02a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.arrow.waves-effect</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='menu']/div/ul/li[3]/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2abcd8f8-4423-4e50-a23d-796b656fe9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arrow waves-effect</value>
      <webElementGuid>a1cc42fc-bad3-4e76-9c79-a83c28cb8631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://phptravels.com/integrations</value>
      <webElementGuid>1d1076ed-aa5d-4829-8ff5-dfb477f14834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Integrations</value>
      <webElementGuid>aedc18ff-013a-432d-9efa-2b958275a9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu&quot;)/div[@class=&quot;nav_left&quot;]/ul[1]/li[3]/div[@class=&quot;link&quot;]/div[@class=&quot;dropdown-content&quot;]/a[@class=&quot;arrow waves-effect&quot;]</value>
      <webElementGuid>5b46596e-33bc-42b7-a6d5-41b78c52752d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/div/ul/li[3]/div/div/a[2]</value>
      <webElementGuid>629a226c-8a1b-4406-a4ac-e314f3576569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Integrations')]</value>
      <webElementGuid>9b7c29bf-a4fa-4321-a528-c25a1aba96bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product'])[1]/following::a[2]</value>
      <webElementGuid>bb3df3eb-2829-4713-a1fa-57563f3de07f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pricing'])[1]/following::a[2]</value>
      <webElementGuid>501e938d-f30e-4041-b4ab-8361ffeb0940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customizations'])[1]/preceding::a[1]</value>
      <webElementGuid>848857db-fd0e-46e1-837e-bb15552e60bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Technology'])[1]/preceding::a[2]</value>
      <webElementGuid>a98af8ca-00a2-40ef-9327-93d1ae427451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Integrations']/parent::*</value>
      <webElementGuid>17974266-a7b1-4315-8a8b-dfb5ecff7e11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://phptravels.com/integrations')]</value>
      <webElementGuid>19bc7646-3501-4ee1-a4d8-17970afaffca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>ed5833fe-f569-4b4c-84f8-d11dbc48ced4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://phptravels.com/integrations' and (text() = 'Integrations' or . = 'Integrations')]</value>
      <webElementGuid>dd822b48-1d2e-4141-9b9a-3c559d524e34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
