<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAttachFile</name>
   <tag></tag>
   <elementGuidId>b70e486f-f847-40f9-bb95-fad58bc6286e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.VizExIconButton__AbstractVizExIconButton-im1tv5-0.eQvYjF</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div[2]/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cfb4f97e-191b-4328-b042-718c59db4a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>attach a file</value>
      <webElementGuid>89046253-660b-4196-add0-d38043d3569f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>shape</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>85a0a9c5-068e-4a44-a53d-2c8dbb5e981f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>AttachmentPickerButton-VizExIconButton</value>
      <webElementGuid>ef37b544-44a8-410a-8ea7-394b4ffaf84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>VizExIconButton__AbstractVizExIconButton-im1tv5-0 eQvYjF</value>
      <webElementGuid>c929a1ca-a730-44bc-b32c-075634c23377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>react-aria6332062418-2</value>
      <webElementGuid>aa6ecf5b-b018-4071-80f3-149c40b478ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current-view-component&quot;)/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetStyleWrapper-q9otpi-0 ikLZth&quot;]/div[@class=&quot;VisitorWidgetStyleWrapper__WidgetContentStyleWrapper-q9otpi-1 gaTWey chat-widget&quot;]/div[@class=&quot;VisitorWidget__WidgetBodyDiv-sc-1casxq4-0 BJKvU&quot;]/div[@class=&quot;UnifiedThreadViewWrapperWithDragUpload__UnifiedThreadViewWrapper-s4ctvh-0 ftjQdo&quot;]/div[@class=&quot;input-container m-bottom-2&quot;]/div[@class=&quot;MessageComposer__InputWrapper-eu8qwr-1 hwHFTi&quot;]/div[@class=&quot;display-flex flex-row m-left-1 no-shrink&quot;]/div[1]/div[@class=&quot;VizExTooltip__PopoverWrapper-c2l1ct-1 ikezbS&quot;]/button[@class=&quot;VizExIconButton__AbstractVizExIconButton-im1tv5-0 eQvYjF&quot;]</value>
      <webElementGuid>4f464d6b-0560-49b1-86c0-60b85d6333d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Exercise4/iframe_concat(id(, , hubspot-conversations-iframe, , ))_hubspot-conversations-iframe</value>
      <webElementGuid>5ac5c1aa-90c8-4578-8134-5072259d3f45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='current-view-component']/div/div/div/div/div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>dc5df8db-5368-402f-a612-cb336fc0237e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='We typically reply in a few minutes'])[2]/following::button[1]</value>
      <webElementGuid>27391210-391e-415a-815a-c45fee60a103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='asdada'])[1]/following::button[2]</value>
      <webElementGuid>15d1d7e3-3cfc-4edf-ba84-9506fc822898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='live chat'])[1]/preceding::button[2]</value>
      <webElementGuid>a56ca1da-2458-4d04-b44d-475f830ce6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/button</value>
      <webElementGuid>cf77332e-e92b-4225-b63a-9c517f5fe233</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
