<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lastFileUpload</name>
   <tag></tag>
   <elementGuidId>107d8a03-0b39-42bc-9968-2f0dfb6d7089</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//b[contains(@class,'VizExFileAttachment__FileName')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
